const path: Record<string, string> = {
    PUBLIC: '',
    HOME: '/',
    ALL: '*',
    VISA_APPLY: 'visa_apply',
    VISA_COUNTRY: 'visa_country',
    FILL_INFO_WEB: 'fill_info_web',
    CHOOSING_PAYMENT_METHOD: 'choosing_payment_method',
    CONFIRM_SUCCESS: 'confirm_success',
    CONFIRM_SUCCESS_TRANSFER: 'confirm_success_transfer',
    CONFIRM_FAIL: 'confirm_fail',
    CONTACT_US: 'contact_us',
    CONTENT_CHECK: 'content_check',
    CONTENT_CHECK_ILLEGAL: 'content_check_legal',
    ABOUT_US: 'about_us',
    CAREER: 'career',
    DETAIL_CAREER: 'detail_career',
    POLICIES: 'policies',
    TERM_AND_CONDITION: 'term_and_condition',
    FAQ: 'faq',
    NEWS: 'news',
    BLOGS: 'blogs',
    BLOG_DETAIL: 'blog_detail',
    MISSING_INFO: 'missing_info',
    COUNTRY_DETAIL: 'country_detail',
    BOOKING_FLIGHT: 'booking_flight',
    SEARCH_FLIGHT: 'search_flight',
    FILL_INFO_DETAIL: 'fill_info_detail',
    REVIEW_INFO: 'review_info',
    PAYMENT: 'payment_page',

    //USER LAYOUT
    USER: 'user',
    MY_ACCOUNT: 'account',
    BOOKING: 'booking',
    BOOKING_DETAIL: 'booking_detail',
    INVOICE: 'invoice',
    PROFILE: 'profile',
}

export default path